version: "2"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./orcidflask/saml/certs:/opt/orcid_integration/orcidflask/saml/certs
      - ./orcidflask/saml/settings.json:/opt/orcid_integration/orcidflask/saml/settings.json
      - ./config.py:/opt/orcid_integration/config.py